version: '3.5'

services:
  postgres:
    container_name: "event_menagement"
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: event_menagement
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  data: